### ISSUE TITLE
Skype for business CU8

### ISSUE THREAD

**Issue by torpedo86** [OfficeDev/skype-web-sdk-samples#39]
I have successfully installed SFBS 2015 6.0.9319.537.
I have this test project "https://github.com/OfficeDev/skype-web-sdk-samples/tree/master/SkypeWebSDKOnPremSample" with skype web sdk, then I have run videoservice.start() so the response was timeout, with CU7 I did not have this problem. Following the code: $('#startNewVideoMeeting').click(function () {         
var conv, dfd, meetingUri, error;         
conv = client.conversationsManager.createConversation();               
$('#newMeetingUri').val("");        
dfd = conv.videoService.start().then(function () {                   
meetingUri = conv.uri();                                                                      $
('#newMeetingUri').val(meetingUri);                  
 $(".c-add-p-container").removeClass('hide'); },          
  function (reason) {                    
// rejection error = reason;            
}); }); 
Response: Code: InvitationFailed 
Error: The operation was timed out. at Anonymous function (https://latestswx.cdn.skype.com/jLync/master_0.4.940/sdk.js:25361:41) at Task.prototype.exec2 (https://latest-swx.cdn.skype.com/jLync/master_0.4.940/sdk.js:5721:29)
 Description: The operation was timed out. 
Can you help me, please? 
Best regards Francesco

**Comment by premgan** [comment]
can you collect console and Fiddler logs from a repro following the steps here:

https://docs.microsoft.com/en-us/skype-sdk/websdk/docs/troubleshooting/gatheringlogs/logs-console

https://docs.microsoft.com/en-us/skype-sdk/websdk/docs/troubleshooting/gatheringlogs/logs-webtraffic

 

We need to know what the SDK is waiting for when it times out.

**Comment by torpedo86** [comment]
My problem is defined in this link:

https://support.microsoft.com/en-us/help/4513510/ucwa-client-cannot-make-a-call-or-join-a-meeting-after-installing-cu8
